defaultPortal: DEVTEST
portals:
  - name: DEVTEST
    portalId: 25504338
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CK7mquXOMBIJAAkAAAAA4A0DGNLUlAwgrLm9DSju6QwyFG89lX4xzuJt9o_R-qPV7dXkhlYxOjcAAABBAAAAeAAAAAAAAAAAAAAAAAAAAAAAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRM9NQsLcQFTjW9fbMrWdmnJxxtFkoDZXUxUgBaAA
        expiresAt: '2022-12-07T12:58:40.817Z'
    personalAccessKey: >-
      CiRldTEtNWUzOC0xZDJhLTQyMjgtYmFmYS1jOWZlM2IwOWU2ODAQ0tSUDBisub0NKhkABeaRgs8hT5efz8qMW6r_btYpfzlh7qR9SgNldTE
