defaultPortal: DEVTEST
portals:
  - name: DEVTEST
    portalId: 25504338
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKSDouTOMBIJAAkAAAAA4A0DGNLUlAwgrLm9DSju6QwyFKnz0Jm3w0V8Q7rOn16ho7Z22-ADOjcAAABBAAAAeAAAAAAAAAAAAAAAAAAAAAAAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRK7PHTTNxkm_4BWtt8krVJCuQBg0oDZXUxUgBaAA
        expiresAt: '2022-12-07T12:21:19.912Z'
    personalAccessKey: >-
      CiRldTEtNWUzOC0xZDJhLTQyMjgtYmFmYS1jOWZlM2IwOWU2ODAQ0tSUDBisub0NKhkABeaRgs8hT5efz8qMW6r_btYpfzlh7qR9SgNldTE
