defaultPortal: DEVTEST
portals:
  - name: DEVTEST
    portalId: 25504338
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNuTxJO6MBIJAAkAAAAA4A0DGNLUlAwgrLm9DSju6QwyFAu1SgeAjRzczZv0k5p6EJ1PIbsPOjcAAABBAAAAeAAAAAAAAAAAAAAAAAAAAAAAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRnkjfpfwaLg9NjeKkGbC-0CmA_NUoDZXUxUgBaAA
        expiresAt: '2022-10-04T10:01:00.640Z'
    personalAccessKey: >-
      CiRldTEtNWUzOC0xZDJhLTQyMjgtYmFmYS1jOWZlM2IwOWU2ODAQ0tSUDBisub0NKhkABeaRgs8hT5efz8qMW6r_btYpfzlh7qR9SgNldTE
